name: BC

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.11
    - name: Install dependencies
      run: |
        cp config.py-example wtosbc/config.py
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Test
      run: |
        pip install pytest-cov
        pytest --cov=wtosbc tests/ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.codecov_token }}
        file: ./coverage.xml
        fail_ci_if_error: true
